# Generated by Django 3.0.5 on 2020-05-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimg',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, unique=True),
        ),
    ]
