# Generated by Django 3.0.5 on 2020-05-13 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_uploadimg_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=150, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=150, unique=True)),
                ('body', models.FileField(upload_to='video/')),
            ],
        ),
        migrations.AlterField(
            model_name='uploadimg',
            name='title',
            field=models.CharField(db_index=True, max_length=150, unique=True),
        ),
    ]
