# Generated by Django 3.0.5 on 2020-09-17 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20200513_1411'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadVideo',
        ),
    ]
